apiVersion: v1
kind: Pod
metadata:
  name: test-configmap-pod
spec:
  containers:
    - name: test-container
      image: k8s.gcr.io/busybox
      command: [ "/bin/sh", "-c", "env" ]
      env:
        - name: MYCONFIGMAP_INFORMATION
          valueFrom:
            configMapKeyRef:
              name: test
              key: configmap.properties
  restartPolicy: Never
